version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: markdown-it
    versions:
    - 12.0.4
    - 12.0.5
  - dependency-name: vuepress
    versions:
    - 1.8.0
    - 1.8.1
  - dependency-name: js-yaml
    versions:
    - 4.0.0
